CREATE TABLE IF NOT EXISTS beneficiarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    chave_principal VARCHAR(50),
    subchave_principal VARCHAR(100),
    nome_completo VARCHAR(100),
    nome_social VARCHAR(100),
    cnpj VARCHAR(20),
    cpf VARCHAR(20),
    email VARCHAR(100),
    telefone VARCHAR(20),
    tel_usuario VARCHAR(20),
    dt_nascimento_usuario DATE,
    endereco VARCHAR(255),
    uf VARCHAR(5),
    cidade VARCHAR(100),
    bairro VARCHAR(100),
    cep VARCHAR(15),
    endereco_risco VARCHAR(255),
    uf_risco VARCHAR(5),
    cidade_risco VARCHAR(100),
    bairro_risco VARCHAR(100),
    cep_risco VARCHAR(15),
    telefone_risco VARCHAR(20),
    raca_animal VARCHAR(100),
    dt_nascimento_animal DATE,
    status VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);